lzc-sdk-version: "0.1"
name: Bin
package: cloud.lazycat.app.wantguns-bin
version: 2.4.0
description: highly opinionated, minimal pastebin
homepage: https://github.com/wantguns/bin
author: wantguns
application:
  subdomain: wantguns-bin
  background_task: true
  public_path:
    - /
  routes:
    - /=http://wantguns-bin:6162/
services:
  wantguns-bin:
    image: registry.lazycat.cloud/czyt/wantguns/bin:65fa262aa6701401
    environment:
      - ROCKET_PORT=6162
      - THEME=
      - HOST_URL=${LAZYCAT_APP_DOMAIN}
    binds:
      - /lzcapp/var/upload:/app/upload
